POST http://localhost:3001/api/user
Content-Type: application/json

{
    "name":"eyasu3",
    "phone":"3",
    "password":"12345"
}
###
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    
    "email":"1@gmail.com",
    "password":"12345"
}
###
GET http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2ZjMDMwODRkZWNiZmE5Njg3ZDFhMCIsImlhdCI6MTY5ODgwMDU1NCwiZXhwIjoxNjk4ODA0MTU0fQ.sH34VvY_829TaYLfNxY7I026erZOQWkwq22j_Pk3HOE

{
    
    "email":"eyasu@bla",
    "password":"12345"
}
###
post http://localhost:3001/api/message
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDNlZDMwY2ZlMGRlMzM4YTM3MTE1YSIsImlhdCI6MTY5OTA1MTk3OSwiZXhwIjoxNjk5MTM4Mzc5fQ.lY6K0fIv6ylo1haim-LCT-_oDsZSyxOJxQGNMabUE_w

{
    "content":"hello",
    "chatId": "6545681889d8dea972e9092b"
}
###
post http://localhost:3001/api/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDZlMGIxY2Q2MmYxYzg1Y2FmNDRjOCIsImlhdCI6MTY5OTE0ODA0NX0.UKMCNYKLmXNXrzcsqP5pC9eFBlXqFf3USgCwPXEIUaI

{
    "phone":"1"
}